export const snow = [
  {
      "id": 1,
      "resort": "Arapahoe Basin",
      "true_snow": 314,
      "days_over6inches": 10.4,
      "months_over90": 6.4,
      "months_under30": 23.2,
      "snow_score": 78.2,
      "new_snow": 5,
      "area_open": 100,
      "base": 60,
      "bva": 82
  },
  {
      "id": 2,
      "resort": "Aspen Snowmass",
      "true_snow": 295,
      "days_over6inches": 10.7,
      "months_over90": 4.4,
      "months_under30": 19.6,
      "snow_score": 74.3,
      "new_snow": 0,
      "area_open": 100,
      "base": 81,
      "bva": 84
  },
  {
      "id": 3,
      "resort": "Beaver Creek",
      "true_snow": 325,
      "days_over6inches": 12.1,
      "months_over90": 8.3,
      "months_under30": 13.1,
      "snow_score": 77.4,
      "new_snow": 0,
      "area_open": 100,
      "base": 56,
      "bva": 86
  },
  {
      "id": 4,
      "resort": "Breckenridge",
      "true_snow": 282,
      "days_over6inches": 11.3,
      "months_over90": 5.4,
      "months_under30": 17.5,
      "snow_score": 70.6,
      "new_snow": 0,
      "area_open": 95,
      "base": 64,
      "bva": 87
  },
  {
      "id": 5,
      "resort": "Copper Mountain",
      "true_snow": 278,
      "days_over6inches": 10.5,
      "months_over90": 3.8,
      "months_under30": 21.1,
      "snow_score": 74.1,
      "new_snow": 0,
      "area_open": 88,
      "base": 49,
      "bva": 84
  },
  {
      "id": 6,
      "resort": "Crested Butte",
      "true_snow": 253,
      "days_over6inches": 9.7,
      "months_over90": 5.5,
      "months_under30": 38,
      "snow_score": 61.7,
      "new_snow": 1,
      "area_open": 74,
      "base": 57,
      "bva": 82
  },
  {
      "id": 7,
      "resort": "Eldora",
      "true_snow": 225,
      "days_over6inches": 9,
      "months_over90": 2,
      "months_under30": 35,
      "snow_score": 61.8,
      "new_snow": 2,
      "area_open": 100,
      "base": 60,
      "bva": 111
  },
  {
      "id": 8,
      "resort": "Keystone",
      "true_snow": 235,
      "days_over6inches": 8.9,
      "months_over90": 0,
      "months_under30": 34.3,
      "snow_score": 63,
      "new_snow": 0,
      "area_open": 99,
      "base": 58,
      "bva": 86
  },
  {
      "id": 9,
      "resort": "Loveland Ski Area",
      "true_snow": 344,
      "days_over6inches": 12.6,
      "months_over90": 11.6,
      "months_under30": 11,
      "snow_score": 80.5,
      "new_snow": 5,
      "area_open": 94,
      "base": 62,
      "bva": 85
  },
  {
      "id": 10,
      "resort": "Monarch Mountain",
      "true_snow": 284,
      "days_over6inches": 11,
      "months_over90": 4.8,
      "months_under30": 22.4,
      "snow_score": 72.4,
      "new_snow": 0,
      "area_open": 98,
      "base": 60,
      "bva": 97
  },
  {
      "id": 11,
      "resort": "Powderhorn",
      "true_snow": 225,
      "days_over6inches": 9,
      "months_over90": 2,
      "months_under30": 35,
      "snow_score": 61.3,
      "new_snow": 0,
      "area_open": 98,
      "base": 46,
      "bva": 87
  },
  {
      "id": 12,
      "resort": "Purgatory",
      "true_snow": 264,
      "days_over6inches": 10,
      "months_over90": 6.8,
      "months_under30": 31.2,
      "snow_score": 65.7,
      "new_snow": 0,
      "area_open": 99,
      "base": 62,
      "bva": 97
  },
  {
      "id": 13,
      "resort": "Ski Granby Ranch",
      "true_snow": 200,
      "days_over6inches": 8,
      "months_over90": 1,
      "months_under30": 40,
      "snow_score": 51.5,
      "new_snow": 0,
      "area_open": 62,
      "base": 28,
      "bva": 98
  },
  {
      "id": 14,
      "resort": "Steamboat",
      "true_snow": 368,
      "days_over6inches": 14.1,
      "months_over90": 16.6,
      "months_under30": 8.3,
      "snow_score": 74.2,
      "new_snow": 0,
      "area_open": 98,
      "base": 75,
      "bva": 84
  },
  {
      "id": 15,
      "resort": "Sunlight",
      "true_snow": 232,
      "days_over6inches": 9.5,
      "months_over90": 2.7,
      "months_under30": 35.1,
      "snow_score": 61.7,
      "new_snow": 0,
      "area_open": 100,
      "base": 48,
      "bva": 87
  },
  {
      "id": 16,
      "resort": "Telluride",
      "true_snow": 276,
      "days_over6inches": 10.8,
      "months_over90": 4.8,
      "months_under30": 23.1,
      "snow_score": 70.2,
      "new_snow": 0,
      "area_open": 93,
      "base": 67,
      "bva": 100
  },
  {
      "id": 17,
      "resort": "Vail",
      "true_snow": 354,
      "days_over6inches": 13.9,
      "months_over90": 18.2,
      "months_under30": 10.7,
      "snow_score": 78.3,
      "new_snow": 0,
      "area_open": 100,
      "base": 63,
      "bva": 81
  },
  {
      "id": 18,
      "resort": "Winter Park",
      "true_snow": 347,
      "days_over6inches": 13.4,
      "months_over90": 10.4,
      "months_under30": 9.3,
      "snow_score": 82.1,
      "new_snow": 0,
      "area_open": 98,
      "base": 84,
      "bva": 101
  },
  {
      "id": 19,
      "resort": "Wolf Creek",
      "true_snow": 387,
      "days_over6inches": 14.9,
      "months_over90": 27.1,
      "months_under30": 18.6,
      "snow_score": 86.1,
      "new_snow": 0,
      "area_open": 100,
      "base": 119,
      "bva": 113
  }
]
